### ISSUE TITLE
US 02.05.01 Filter item in list by date

### ISSUE THREAD

**Issue by HuuDinhKyNguyen** [CMPUT301F23T31/LetsGoGolfing#10]
### **User Story**
As an owner, I want to filter the list of items by date range.

### **Description**
The owner must be able to filter personal item list by date range. The dates stored are assumed to be of a particular format and empty date fields do not show up in any filter prompts.

### **Acceptance Criteria:**
- Users should be able to select a start and end date to filter items.
- The item list should update to show only items within the selected date range.
- Ensure the filter interacts correctly with other existing filters.

### **Tasks**
- [x] #103 
- [x] #104 
- [x] #105 
- [x] #106 
- [x] #107 

**Risk Level: Low**
**Size: 2**

**Comment by jordanisaac1** [comment]
good job guys
