### ISSUE TITLE
US 02.06.01 Filter item list by description keywords

### ISSUE THREAD

**Issue by HuuDinhKyNguyen** [CMPUT301F23T31/LetsGoGolfing#11]
### **User Story**
As an owner, I want to filter the list of items by description keywords.

### **Description**
The owner must be able to filter personal item list by description keywords. Item description fields are optional upon creation of an item and items with empty descriptions won't show up on any filter prompts.  

### **Acceptance Criteria:**
- Users should be able to enter keywords to filter items.
- The item list should update to show only items that match the entered keywords in their description.
- Ensure the filter interacts correctly with other existing filters.

### **Tasks**
- [x] #108 
- [x] #109 
- [x] #110 
- [x] #111 
- [x] #112 

**Risk Level: Medium**
**Size: 2**

**Comment by jordanisaac1** [comment]
awesome job
