### ISSUE TITLE
US 02.07.01 Filter item list by make

### ISSUE THREAD

**Issue by HuuDinhKyNguyen** [CMPUT301F23T31/LetsGoGolfing#12]
### **User Story**
As an owner, I want to filter the list of items by make.

### **Description**
The owner must be able to filter personal item list by make. The filter is assumed to return all items that has make containing the keyword searched instead of only returning exact matches.

### **Acceptance Criteria:**
- Users should be able to select or enter a make to filter items.
- The item list should update to show only items that match the selected or entered make.
- Ensure the filter interacts correctly with other existing filters.

### **Tasks**
- [x] #113 
- [x] #114 
- [x] #115 
- [x] #116 
- [x] #117 

**Risk Level: Low**
**Size: 2**

**Comment by jordanisaac1** [comment]
this looks great
