### ISSUE TITLE
US 04.01.01 Taking and Attaching Photos to Items

### ISSUE THREAD

**Issue by jordanisaac1** [CMPUT301F23T31/LetsGoGolfing#19]
## User Story
As an owner, I want to take photos using the camera from the app, and attach one or more photographs to an item of mine.

## Description
What's it all about?
* Similar to being able to add a tag, the user must be able to add an image to an item
We need to be able to allow the user to click on a camera button that will allow the user to take a photo, and then give them the ability to attach it to an item that is in their owned item list. This is considered medium-risk since it will be manipulating the item data and will have to handle more than one image entry, along with assigning and updating the selected item.

#### **Acceptance Criteria:**
- Users should be able to take photos directly within the app.
- Users should be able to attach these photos to their items.
- Ensure that the photo attachment process is user-friendly and efficient.

#### Progress
- [x] #128 
- [x] #129 
- [x] #130 
- [x] #131 
- [x] #132 

**Risk Level: Medium-Risk**
**Size: 4**

**Comment by vedanttalati** [comment]
TA Approved milestone change, unrealistic expectation for the application so far.

**Comment by jordanisaac1** [comment]
this is great
