### ISSUE TITLE
US 05.01.01 Scanning Serial Number from Image

### ISSUE THREAD

**Issue by jordanisaac1** [CMPUT301F23T31/LetsGoGolfing#22]
## User Story
 help to specify the serial number for an item by automatically identifying the number from an image taken by the camera
## Description
**What's it all about?**

By scanning an item's image, the system can detect and populate its serial number, reducing manual input and potential errors.

#### **Acceptance Criteria:**
- Users should be able to take a photo of an item's serial number.
- The app should automatically identify and extract the serial number from the image.
- The identified serial number should be accurately populated in the item's details.

#### **Tasks**
- [ ] #143 
- [ ] #144 
- [ ] #145 
- [ ] #146 
- [ ] #147

**Risk Level: Low risk**
**Size: 3**

**Comment by leviLThomas** [comment]
We decided that using computer vision was outside the scope of the project. Serial numbers are extracted from scanned barcodes.
