### ISSUE TITLE
US 01.01.02 Create Item Model

### ISSUE THREAD

**Issue by leviLThomas** [CMPUT301F23T31/LetsGoGolfing#28]
## Description
Create a Java class to represent the Item entity with the necessary fields as per US 01.01.01.

## Acceptance Criteria
- The Item class must include the following fields:
  - Date of purchase
  - Brief description
  - Make
  - Model
  - Serial number (optional)
  - Estimated value
  - Comment
- The class should include methods for setting and getting these properties.
- Unit tests to validate the model's behavior.

**Comment by jordanisaac1** [comment]
Wrote and passed test cases for item class
