### ISSUE TITLE
US 01.03.05 Write Tests for Editing Item Details

### ISSUE THREAD

**Issue by leviLThomas** [CMPUT301F23T31/LetsGoGolfing#40]
## Description
Write unit and integration tests to cover the editing of item details.

## Acceptance Criteria
- Unit tests for input validation logic.
- Integration tests for the update operation with Firestore.
- Mocking Firestore for testing the update operation.
- All tests should pass successfully.

**Comment by jordanisaac1** [comment]
done and working
