### ISSUE TITLE
US 01.04.03 Implement Logic for Deleting an Item from Inventory

### ISSUE THREAD

**Issue by leviLThomas** [CMPUT301F23T31/LetsGoGolfing#43]
## Description
Implement the functionality that allows users to delete an item from their inventory within the Fragment or Activity.

## Acceptance Criteria
- When the user confirms deletion, the item should be removed from the displayed list.
- The UI should update to reflect the removal of the item.
- Include proper error handling for the delete operation.

**Comment by jordanisaac1** [comment]
Migrated to new current branch
