### ISSUE TITLE
US 01.04.06 Implement Navigation and Workflow for Deleting Items

### ISSUE THREAD

**Issue by leviLThomas** [CMPUT301F23T31/LetsGoGolfing#46]
## Description
Handle the workflow that allows users to delete an item from the item detail view or the item list.

## Acceptance Criteria
- Include a 'Delete' option in the item detail view and/or next to each item in the list.
- Ensure that the confirmation dialog appears when the 'Delete' option is selected.
- After deletion, navigate the user away from the deleted item's detail view if applicable.

## Note
This feature could be combined with #8 if the user can select and delete a single item as well as many then this criteria is satisfied

**Comment by jordanisaac1** [comment]
migrated to new branch
