### ISSUE TITLE
US 01.04.01: Delete an item

### ISSUE THREAD

**Issue by leviLThomas** [CMPUT301F23T31/LetsGoGolfing#5]
## User Story
As an owner, I want to delete an item.

## Description
The user must be able to select and delete an item. References to the item will be deleted from the database and removed from the item list.

## Tasks
- [x] #42 
- [x] #43 
- [x] #44 
- [x] #45 
- [x] #46

Risk Level: High
Size: 2

**Comment by jordanisaac1** [comment]
fully functional, select multiple and delete multiple items
