### ISSUE TITLE
US 02.01.06 Write Integration Tests for Displaying Item List

### ISSUE THREAD

**Issue by leviLThomas** [CMPUT301F23T31/LetsGoGolfing#51]
## Description
Write integration tests to verify that the item list is properly displayed as fetched from Firestore.

## Acceptance Criteria
- Tests should verify that the list is populated with items from Firestore.
- Tests should handle different states of the list, including empty and populated states.
- All tests should pass successfully.

**Comment by jordanisaac1** [comment]
done
