### ISSUE TITLE
US 02.03.05 Write Tests for Multi-Selection and Bulk Deletion Logic

### ISSUE THREAD

**Issue by leviLThomas** [CMPUT301F23T31/LetsGoGolfing#59]
## Description
Write tests to ensure that the multi-selection and bulk deletion logic is functioning correctly.

## Acceptance Criteria
- Tests should cover the selection mechanism, ensuring items can be selected and deselected correctly.
- Tests should verify that the bulk deletion properly removes items from Firestore and updates the UI.
- All tests should pass successfully.

**Comment by jordanisaac1** [comment]
done
