### ISSUE TITLE
US 02.02.01 Display total estimate value

### ISSUE THREAD

**Issue by HuuDinhKyNguyen** [CMPUT301F23T31/LetsGoGolfing#7]
### **User Story**
As an owner, I want to see the total estimated value of the shown items in the list of items.

### **Description**
The owner must be able to see an estimate of the total value of items shown in personal item list, currently assumed to be shown at all times within the main page and is updated as items are added/edited/removed

### **Tasks**
- [x] #52 
- [x] #53 
- [x] #54 
- [x] #55 

Risk Level: Low
Size: 1

**Comment by jordanisaac1** [comment]
works great
