### ISSUE TITLE
US 02.03.01 Select & Delete selected list item

### ISSUE THREAD

**Issue by HuuDinhKyNguyen** [CMPUT301F23T31/LetsGoGolfing#8]
### **User Story**
As an owner, I want to select items from the list of items and delete the selected items.

### **Description**
The owner must be able to select items in personal item list, currently assumed to be long pressing items fields in main page and selected items will be highlighted as well as additional options will be shown once at least one item is selected.

### **Tasks*
- [x] #56 
- [x] #57 
- [x] #58 
- [x] #59 
- [x] #90 

Risk Level: Medium
Size: 2

**Comment by jordanisaac1** [comment]
done
