### ISSUE TITLE
US 03.02.06 Write Tests for Tag Assignment

### ISSUE THREAD

**Issue by leviLThomas** [CMPUT301F23T31/LetsGoGolfing#84]
**Description:**
Write comprehensive tests to cover the tag assignment functionality. This includes unit tests for the assignment logic and integration tests for database interactions.

**Acceptance Criteria:**
- [ ] Unit tests for tag assignment logic pass.
- [ ] Integration tests with the database pass.

**Comment by jordanisaac1** [comment]
done and tested
