### ISSUE TITLE
US 02.03.06 - Select Feature Deletion Bug

### ISSUE THREAD

**Issue by vedanttalati** [CMPUT301F23T31/LetsGoGolfing#90]
When pressing the select button, and only deleting some items, the select feature would stay on instead of closing out and going back into view mode. Fix by going back into view mode as soon as delete button is pressed or cancel is pressed.

**Comment by leviLThomas** [comment]
Fixed in commit 7209fb19ba910c3006beac8217c826063aed5eab in PR #91
